ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "otp" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "otpExpiry" TIMESTAMP(6);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "otpCount" INTEGER DEFAULT 0;
